version: 2.1
orbs:
  win: circleci/windows@1.0.0
jobs:
  build-and-test-windows:
    executor:
      name: win/vs2019
    steps:
      - checkout
      - run: npm install
      - run: npm test
  build-and-test-macos:
    macos:
      xcode: 11.0.0
    steps:
      - checkout
      - run: npm install
      - run: npm test
  build-and-test-linux:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - run: npm install
      - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test-windows
        - build-and-test-macos
        - build-and-test-linux